#!/usr/bin/env bash
# A Bash script that prints "To infinity and beyond" indefinitely every 2 seconds
trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
